on: [push, pull_request]

name: render
permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R package dependencies.
        run: install.packages(c("distill", "rmarkdown"))
        shell: Rscript {0}

      - name: Render site.
        run: rmarkdown::render_site()
        shell: Rscript {0}

      - name: Deploy to GitHub pages.
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
